backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "src/assets" # Media files
public_folder: "/assets" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    description: "this is a test description"
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template
    fields: # The fields for each document, usually in front matter
      - { label: "title", name: "title", widget: "string" }
  - name: "services"
    label: "Services"
    description: "this is a test description for services"
    folder: "src/content/services"
    create: true
    slug: "{{slug}}" # Filename template
    fields: # The fields for each document, usually in front matter
      - { label: "title", name: "title", widget: "string" }
      - { label: "subtitle", name: "subtitle", widget: "string" }
      - { label: "icon", name: "icon", widget: "image" }
  - name: "portfolio"
    label: "Portfolio"
    description: "this is a test description for portfolio"
    folder: "src/content/portfolio"
    create: true
    slug: "{{slug}}" # Filename template
    fields:
      - { label: "title", name: "title", widget: "string" }
      - { label: "description", name: "description", widget: "string" }
      - { label: "date", name: "date", widget: "datetime" }
      - { label: "url", name: "url", widget: "string" }
      - { label: "hero", name: "hero", widget: "image" }
      - {
          label: "images",
          name: "images",
          widget: "list",
          fields: [{ label: "image", name: "image", widget: "image" }],
        }
      - { label: "body", name: "body", widget: "markdown" }
